# -*- coding: utf-8 -*-
"""Task_3_3_Diabits_disease__diagnostic_bot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qd32bQ5Xkkcb-zc_VIruudlYUeO_SkSF
"""
import warnings
warnings.filterwarnings("ignore")



#=============================================
#data = pd.read_csv('diabets.csv')
#=============================================
# load the model from disk

import pickle

def Run_Diabets_disease_Bot():

    filename_module = './Tache3_make_prediction/C_diabets_disease_prediction/GradientBoostingClassifier_For_diabets_checker.sav'
    gb = pickle.load(open(filename_module, 'rb'))
    
    #=============================================
    # load the scaler model from disk
    
    filename_scaler = './Tache3_make_prediction/C_diabets_disease_prediction/scaler_N2.sav'
    # pickle.dump(scaler, open(filename, 'wb'))
    
    scaler = pickle.load(open(filename_scaler, 'rb'))
    
    #=============================================
    
    
    
    def get_info_Continuous(text , subject):
      print(text)
      while True:
        try:
          variable_intered=float(input(""))
          break
        except:
            print("Can you please Enter a valid ",subject)
      
      return variable_intered
    
    def Diabets_disease_Bot():  
    
      flage =True
      while flage:
        print("hello please anter the folowing mesearmunt in order to predict your statu \n")
        print("enter Yes to contunious the prisougre and No to close \n ")
        continu_pres=""
        while True:
          continu_pres=input("desicion :  ")
          continu_pres=continu_pres.lower()
          if (continu_pres=="no" or continu_pres=="yes"):
            break
          else:
            print("Please inter a valide answer \n ")
    
        if (continu_pres=="no"):
          break
     
        # Pregnancies	Glucose	BloodPressure	SkinThickness	Insulin	BMI	DiabetesPedigreeFunction	Age
    
        user_Pregnancies=get_info_Continuous("please tell me number of Pregnancies if your a male just write 0  \n","Pregnancies level")
        user_glucose=get_info_Continuous("Oky ,please telle me the glucose level in your body \n","glucose level")
        user_BloodPressure=get_info_Continuous("please telle me the  blood pressure in your body \n","diastolic blood pressure")
        user_SkinThickness=get_info_Continuous("What about the SkinThickness in your body \n","systolic blood pressure")
        user_insulin=get_info_Continuous("Oky ,please telle me the insulin level in your body  \n"," insulin ")
        user_BMI=get_info_Continuous("Oky ,please telle me the BMI  \n"," BMI ")
        user_DiabetesPedigreeFunction=get_info_Continuous("Oky ,please telle me the DiabetesPedigreeFunction level  \n","Diabetes Pedigree Function level")
        user_Age=get_info_Continuous("please enter your age  \n" ,"Age")
       
        #sysBP	glucose	age	cigsPerDay	totChol	diaBP	prevalentHyp	male	BPMeds	diabetes 
        #test_user=[[ user_sysBP , user_glucose , Age_user , user_cigsPerDay , user_totChol , user_diaBP , user_prevalentHyp , user_sex , user_bpmeds , user_diabetes ]]
        flage = False
        test_user_valid=[[user_Pregnancies , user_glucose , user_BloodPressure , user_SkinThickness , user_insulin , user_BMI , user_DiabetesPedigreeFunction , user_Age ]]
        test_user_valid = scaler.transform(test_user_valid)
    
        Hd_prediction=gb.predict(test_user_valid)
        if Hd_prediction==1:
          print("the probability that you will have heart disease is 89%")
        else: 
          print("with ur current info , you wont have a diabets disease but try to sty healthy")
    
    def Run_Diabets_disease_Bot_run():
      while True:
        Diabets_disease_Bot()
        print("would you like to do the diagnostic again enter  Yes / No  \n")
        answ=""
        while True:
          answ=input("")
          answ=answ.lower()
          if (answ=="yes" or answ=="no"):
            break
          else:
            print("Please enter a valide answer")
        if answ=="no":
          break
    
    Run_Diabets_disease_Bot_run()